version: '3.5'
services:
  fbng_db:
    container_name: fbng_db
    image: mysql:latest
    hostname: fbng_db
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: 'fbng_db'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'db_pwd'
      MYSQL_ROOT_PASSWORD: 'db_pwd'
    volumes:
      - ./dbdata:/var/lib/mysql:cached
    ports:
      - "6100:3306"
    networks:
      - fbng-net
      - fbng-db-net
  fbng_backend:
    container_name: fbng_backend
    environment:
      DB_NAME: 'fbng_db'
      DB_USER: 'db_user'
      DB_PASSWORD: 'db_pwd'
      DB_HOST: 'fbng_db'
      WAIT_HOSTS: fbng_db:3306
      WAIT_HOSTS_TIMEOUT: 600
    build: backend
    volumes:
      - ../src:/app
      - ./repository:/repository:cached
      - ../src/logs:/app/logs
    networks:
      - fbng-net
      - fbng-db-net
  fbng_frontend:
    container_name: fbng_frontend
    build: frontend
    volumes:
      - ../frontend:/app:cached
    ports:
      - "9040:9040"
    networks:
      - fbng-net
  fbng_nginx:
    container_name: fbng_nginx
    build: nginx
    ports:
      - "9999:8889"
    networks:
      - fbng-net
    depends_on:
      - fbng_backend
      - fbng_frontend
networks:
  fbng-net:
    name: fbng-net
    driver: bridge
  fbng-db-net:
    name: vrwyas-db-net
    driver: bridge
